연습문제

---

In [1]:
import pandas as pd

In [4]:
data = [10,20,30,40,50]
s = pd.Series(data)
s

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [6]:
print(s.tolist())

[10, 20, 30, 40, 50]

In [9]:
a = pd.Series([1, 2, 3, 4])
b = pd.Series([5, 6, 7, 8]) 
print(a+b)
print(a-b)
print(a*b)
print(a/b)

0     6
1     8
2    10
3    12
dtype: int64
0   -4
1   -4
2   -4
3   -4
dtype: int64
0     5
1    12
2    21
3    32
dtype: int64
0    0.200000
1    0.333333
2    0.428571
3    0.500000
dtype: float64

In [12]:
d = {'a': 100, 'b': 200, 'c': 300, 'd': 400} 
s2 = pd.Series(d)
s2

a    100
b    200
c    300
d    400
dtype: int64

In [14]:
import numpy as np

In [17]:
arr = np.array([10, 20, 30]) 
s3 = pd.Series(arr)
s3

0    10
1    20
2    30
dtype: int64

In [25]:
s = pd.Series(['100', '200', 'python', '300.12', '400'])
result = pd.to_numeric(s, errors='coerce')
result

0    100.00
1    200.00
2       NaN
3    300.12
4    400.00
dtype: float64

In [30]:
data = {'col1': [1, 2], 'col2': [3, 4]}
df = pd.DataFrame(data)
df

   col1  col2
0     1     3
1     2     4

In [31]:
s_name = pd.Series(['Amy', 'Bob', 'Chris'])
s_age = pd.Series([25, 30, 22])
df_info = pd.DataFrame({'Name': s_name, 'Age': s_age})
df_info

    Name  Age
0    Amy   25
1    Bob   30
2  Chris   22

In [33]:
df_info.index = ['id_1', 'id_2', 'id_3']
df_info

       Name  Age
id_1    Amy   25
id_2    Bob   30
id_3  Chris   22

In [36]:
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
result = pd.DataFrame(arr2d, columns = ['A', 'B', 'C'])
result

   A  B  C
0  1  2  3
1  4  5  6

In [39]:
data_list = [{'name': 'John', 'age': 25}, {'name': 'Jane', 'age': 30}]
result = pd.DataFrame(data_list)
result

   name  age
0  John   25
1  Jane   30

In [42]:
dates = pd.date_range('20230101', periods=6)
dates

DatetimeIndex(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04',
               '2023-01-05', '2023-01-06'],
              dtype='datetime64[us]', freq='D')

In [64]:
df_dates = pd.DataFrame(np.random.randn(6, 4), index = dates, columns=['A', 'B', 'C', 'D'])
df_dates

                   A         B         C         D
2023-01-01 -0.173499  0.241069  0.309817  0.381852
2023-01-02  2.437882  0.825067 -0.478847 -1.204141
2023-01-03 -0.286264 -1.131888  1.782014  0.014580
2023-01-04  1.355699 -1.093151 -0.483498 -2.062366
2023-01-05  0.858449 -0.216193 -0.824854 -0.431803
2023-01-06  0.839216 -0.769843 -0.389715 -0.465770

In [70]:
df_dates.head(3)

                   A         B         C         D
2023-01-01 -0.173499  0.241069  0.309817  0.381852
2023-01-02  2.437882  0.825067 -0.478847 -1.204141
2023-01-03 -0.286264 -1.131888  1.782014  0.014580

In [73]:
print(df_dates.columns)
print(df_dates.index)

Index(['A', 'B', 'C', 'D'], dtype='str')
DatetimeIndex(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04',
               '2023-01-05', '2023-01-06'],
              dtype='datetime64[us]', freq='D')

In [75]:
df_dates.describe()

              A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean   0.838581 -0.357490 -0.014180 -0.627941
std    1.011450  0.785825  0.955582  0.881688
min   -0.286264 -1.131888 -0.824854 -2.062366
25%    0.079679 -1.012324 -0.482335 -1.019548
50%    0.848832 -0.493018 -0.434281 -0.448786
75%    1.231387  0.126754  0.134934 -0.097016
max    2.437882  0.825067  1.782014  0.381852

In [77]:
df_dates.sort_values(by='B', ascending=False)

                   A         B         C         D
2023-01-02  2.437882  0.825067 -0.478847 -1.204141
2023-01-01 -0.173499  0.241069  0.309817  0.381852
2023-01-05  0.858449 -0.216193 -0.824854 -0.431803
2023-01-06  0.839216 -0.769843 -0.389715 -0.465770
2023-01-04  1.355699 -1.093151 -0.483498 -2.062366
2023-01-03 -0.286264 -1.131888  1.782014  0.014580

In [82]:
df_dates['A']

2023-01-01   -0.173499
2023-01-02    2.437882
2023-01-03   -0.286264
2023-01-04    1.355699
2023-01-05    0.858449
2023-01-06    0.839216
Freq: D, Name: A, dtype: float64

In [86]:
print(df_dates[0:3])

                   A         B         C         D
2023-01-01 -0.173499  0.241069  0.309817  0.381852
2023-01-02  2.437882  0.825067 -0.478847 -1.204141
2023-01-03 -0.286264 -1.131888  1.782014  0.014580

In [88]:
df_dates['2023-01-02':'2023-01-04']

                   A         B         C         D
2023-01-02  2.437882  0.825067 -0.478847 -1.204141
2023-01-03 -0.286264 -1.131888  1.782014  0.014580
2023-01-04  1.355699 -1.093151 -0.483498 -2.062366

In [93]:
df_dates.loc[dates[0]]

A   -0.173499
B    0.241069
C    0.309817
D    0.381852
Name: 2023-01-01 00:00:00, dtype: float64

In [101]:
df_dates.loc[:, ['A','B']]

                   A         B
2023-01-01 -0.173499  0.241069
2023-01-02  2.437882  0.825067
2023-01-03 -0.286264 -1.131888
2023-01-04  1.355699 -1.093151
2023-01-05  0.858449 -0.216193
2023-01-06  0.839216 -0.769843

In [104]:
df_dates.iloc[3]

A    1.355699
B   -1.093151
C   -0.483498
D   -2.062366
Name: 2023-01-04 00:00:00, dtype: float64

In [108]:
df_dates.iloc[3:5, 0:2]

                   A         B
2023-01-04  1.355699 -1.093151
2023-01-05  0.858449 -0.216193

In [110]:
df_dates[df_dates['A'] > 0]

                   A         B         C         D
2023-01-02  2.437882  0.825067 -0.478847 -1.204141
2023-01-04  1.355699 -1.093151 -0.483498 -2.062366
2023-01-05  0.858449 -0.216193 -0.824854 -0.431803
2023-01-06  0.839216 -0.769843 -0.389715 -0.465770

In [112]:
df_dates[df_dates > 0]

                   A         B         C         D
2023-01-01       NaN  0.241069  0.309817  0.381852
2023-01-02  2.437882  0.825067       NaN       NaN
2023-01-03       NaN       NaN  1.782014  0.014580
2023-01-04  1.355699       NaN       NaN       NaN
2023-01-05  0.858449       NaN       NaN       NaN
2023-01-06  0.839216       NaN       NaN       NaN

In [114]:
df_dates['E'] = ['one', 'one', 'two', 'three', 'four', 'three']
df_dates

                   A         B         C         D      E
2023-01-01 -0.173499  0.241069  0.309817  0.381852    one
2023-01-02  2.437882  0.825067 -0.478847 -1.204141    one
2023-01-03 -0.286264 -1.131888  1.782014  0.014580    two
2023-01-04  1.355699 -1.093151 -0.483498 -2.062366  three
2023-01-05  0.858449 -0.216193 -0.824854 -0.431803   four
2023-01-06  0.839216 -0.769843 -0.389715 -0.465770  three

In [118]:
df_dates.loc[(df_dates['E'] =='two') | (df_dates['E'] =='four')]

                   A         B         C         D     E
2023-01-03 -0.286264 -1.131888  1.782014  0.014580   two
2023-01-05  0.858449 -0.216193 -0.824854 -0.431803  four

In [121]:
df_dates.iloc[0,0] = 100
df_dates

                     A         B         C         D      E
2023-01-01  100.000000  0.241069  0.309817  0.381852    one
2023-01-02    2.437882  0.825067 -0.478847 -1.204141    one
2023-01-03   -0.286264 -1.131888  1.782014  0.014580    two
2023-01-04    1.355699 -1.093151 -0.483498 -2.062366  three
2023-01-05    0.858449 -0.216193 -0.824854 -0.431803   four
2023-01-06    0.839216 -0.769843 -0.389715 -0.465770  three

In [123]:
df_dates.iloc[4,1] = np.nan
df_dates.dropna(how='any')

                     A         B         C         D      E
2023-01-01  100.000000  0.241069  0.309817  0.381852    one
2023-01-02    2.437882  0.825067 -0.478847 -1.204141    one
2023-01-03   -0.286264 -1.131888  1.782014  0.014580    two
2023-01-04    1.355699 -1.093151 -0.483498 -2.062366  three
2023-01-06    0.839216 -0.769843 -0.389715 -0.465770  three

In [125]:
df_dates.fillna(0)

                     A         B         C         D      E
2023-01-01  100.000000  0.241069  0.309817  0.381852    one
2023-01-02    2.437882  0.825067 -0.478847 -1.204141    one
2023-01-03   -0.286264 -1.131888  1.782014  0.014580    two
2023-01-04    1.355699 -1.093151 -0.483498 -2.062366  three
2023-01-05    0.858449  0.000000 -0.824854 -0.431803   four
2023-01-06    0.839216 -0.769843 -0.389715 -0.465770  three

In [137]:
df_dates.describe()

                A         B         C         D
count    6.000000  5.000000  6.000000  6.000000
mean    17.534164 -0.385749 -0.014180 -0.627941
std     40.409462  0.875164  0.955582  0.881688
min     -0.286264 -1.131888 -0.824854 -2.062366
25%      0.844024 -1.093151 -0.482335 -1.019548
50%      1.107074 -0.769843 -0.434281 -0.448786
75%      2.167337  0.241069  0.134934 -0.097016
max    100.000000  0.825067  1.782014  0.381852

In [141]:
df_dates.index

DatetimeIndex(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04',
               '2023-01-05', '2023-01-06'],
              dtype='datetime64[us]', freq='D')

In [142]:
df_dates.columns

Index(['A', 'B', 'C', 'D', 'E'], dtype='str')

In [140]:
df_dates.describe().loc["mean", :]

A    17.534164
B    -0.385749
C    -0.014180
D    -0.627941
Name: mean, dtype: float64

In [153]:
df_dates[['A', 'B', 'C', 'D']].mean(axis=1)

2023-01-01    25.233185
2023-01-02     0.394990
2023-01-03     0.094611
2023-01-04    -0.570829
2023-01-05    -0.132736
2023-01-06    -0.196528
Freq: D, dtype: float64

In [155]:
df_dates.apply(np.cumsum)

                     A         B         C         D                        E
2023-01-01  100.000000  0.241069  0.309817  0.381852                      one
2023-01-02  102.437882  1.066137 -0.169030 -0.822289                   oneone
2023-01-03  102.151618 -0.065751  1.612984 -0.807709                oneonetwo
2023-01-04  103.507318 -1.158903  1.129487 -2.870075           oneonetwothree
2023-01-05  104.365767       NaN  0.304633 -3.301878       oneonetwothreefour
2023-01-06  105.204982 -1.928745 -0.085082 -3.767647  oneonetwothreefourthree

In [160]:
data = {'key': ['A', 'B', 'C', 'A', 'B', 'C'], 'data': range(6)}
df_key = pd.DataFrame(data)
df_key.groupby('key').sum()

     data
key
A       3
B       5
C       7

In [162]:
left = pd.DataFrame({'key': ['foo', 'bar'], 'lval': [1, 2]})
right = pd.DataFrame({'key': ['foo', 'bar'], 'rval': [4, 5]})
merge = pd.merge(left, right, on='key')
merge

   key  lval  rval
0  foo     1     4
1  bar     2     5

In [167]:
df_dates.to_csv('foo.csv')

In [171]:
df_loaded = pd.read_csv('foo.csv', index_col=0)
df_loaded

                     A         B         C         D      E
2023-01-01  100.000000  0.241069  0.309817  0.381852    one
2023-01-02    2.437882  0.825067 -0.478847 -1.204141    one
2023-01-03   -0.286264 -1.131888  1.782014  0.014580    two
2023-01-04    1.355699 -1.093151 -0.483498 -2.062366  three
2023-01-05    0.858449       NaN -0.824854 -0.431803   four
2023-01-06    0.839216 -0.769843 -0.389715 -0.465770  three

In [172]:
df = pd.DataFrame(np.random.randn(3, 3), columns=['A', 'B', 'C'])
df.apply(lambda x: x.max() - x.min())

A    1.326114
B    1.593886
C    0.238498
dtype: float64