In [1]:
import pandas as pd
import glob
import os

In [2]:
# 1. CSV 파일들이 들어있는 폴더 경로
folder_path =r"C:\Users\hmabc\Downloads\myd_reviews"

# 2. 해당 폴더 안의 csv 파일 전체 불러오기
file_list = glob.glob(os.path.join(folder_path, "*.csv"))

# 3. 파일명 정렬
file_list = sorted(file_list)

print("불러온 파일 개수:", len(file_list))
print(file_list[:5])

불러온 파일 개수: 31
['C:\\Users\\hmabc\\Downloads\\myd_reviews\\reviews_reviews_io.snplab.myd_202305.csv', 'C:\\Users\\hmabc\\Downloads\\myd_reviews\\reviews_reviews_io.snplab.myd_202306.csv', 'C:\\Users\\hmabc\\Downloads\\myd_reviews\\reviews_reviews_io.snplab.myd_202307.csv', 'C:\\Users\\hmabc\\Downloads\\myd_reviews\\reviews_reviews_io.snplab.myd_202308.csv', 'C:\\Users\\hmabc\\Downloads\\myd_reviews\\reviews_reviews_io.snplab.myd_202309.csv']

In [3]:
file_list[0]

'C:\\Users\\hmabc\\Downloads\\myd_reviews\\reviews_reviews_io.snplab.myd_202305.csv'

In [4]:
pd.read_csv(file_list[0], encoding='utf-16')

,Package Name,App Version Code,App Version Name,Reviewer Language,Device,Review Submit Date and Time,Review Submit Millis Since Epoch,Review Last Update Date and Time,Review Last Update Millis Since Epoch,Star Rating,Review Title,Review Text,Developer Reply Date and Time,Developer Reply Millis Since Epoch,Developer Reply Text,Review Link
0,io.snplab.myd,230427001,2.3.3-prod-rel-202304270020,ko,a8sqlteks,2023-05-01T02:11:40Z,1682907100167,2023-05-01T02:11:40Z,1682907100167,4,NaN,조아요,2023-05-02T06:43:14Z,1.683010e+12,"안녕하세요 모름님, 마이디입니다. 먼저 , 저희 앱을 좋아 해주셔 감사합니다. 앞으...",http://play.google.com/console/developers/8861...
1,io.snplab.myd,230427001,2.3.3-prod-rel-202304270020,ko,o1s,2023-05-01T11:01:02Z,1682938862348,2023-05-01T11:01:02Z,1682938862348,5,NaN,NaN,NaN,NaN,NaN,NaN
2,io.snplab.myd,230427001,2.3.3-prod-rel-202304270020,ko,t2s,2023-05-01T11:57:27Z,1682942247763,2023-05-01T11:57:27Z,1682942247763,5,NaN,NaN,NaN,NaN,NaN,NaN
3,io.snplab.myd,230427001,2.3.3-prod-rel-202304270020,ko,b2q,2023-05-01T12:51:10Z,1682945470101,2023-05-01T12:51:10Z,1682945470101,5,NaN,NaN,NaN,NaN,NaN,NaN
4,io.snplab.myd,230427001,2.3.3-prod-rel-202304270020,ko,g0q,2023-05-02T04:51:40Z,1683003100146,2023-05-02T04:51:40Z,1683003100146,4,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73,io.snplab.myd,230516001,2.3.4-prod-rel-202305162023,ko,p3s,2023-05-28T11:51:20Z,1685274680043,2023-05-28T11:51:20Z,1685274680043,5,NaN,앱테크앱중 수입 제일좋아요,2023-05-31T02:58:21Z,1.685502e+12,"안녕하세요 이현미 님, 마이디입니다. 먼저 , 저희 앱을 이용 해주셔 감사합니다. ...",http://play.google.com/console/developers/8861...
74,io.snplab.myd,230516001,2.3.4-prod-rel-202305162023,ko,r8q,2023-05-30T00:50:22Z,1685407822935,2023-05-30T00:50:22Z,1685407822935,5,NaN,NaN,NaN,NaN,NaN,NaN
75,io.snplab.myd,230516001,2.3.4-prod-rel-202305162023,ko,dm2q,2023-05-31T02:08:00Z,1685498880115,2023-05-31T02:08:00Z,1685498880115,5,NaN,NaN,NaN,NaN,NaN,NaN
76,io.snplab.myd,230516001,2.3.4-prod-rel-202305162023,ko,a10ekx,2023-05-31T07:20:09Z,1685517609782,2023-05-31T07:20:09Z,1685517609782,5,NaN,NaN,NaN,NaN,NaN,NaN
77,io.snplab.myd,230516001,2.3.4-prod-rel-202305162023,ko,dm3q,2023-05-31T22:18:34Z,1685571514600,2023-05-31T22:18:34Z,1685571514600,5,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
import pandas as pd
import glob
import os

folder_path = r"C:\Users\hmabc\Downloads\myd_reviews"

file_list = sorted(glob.glob(os.path.join(folder_path, "*.csv")))

print("찾은 파일 수:", len(file_list))
print(file_list[:3])

df_list = []
failed_files = []

for file in file_list:
    try:
        temp = pd.read_csv(file, encoding="utf-16")
        month = os.path.basename(file).split("_")[-1].replace(".csv", "")
        temp["review_month"] = month
        temp["source_file"] = os.path.basename(file)
        df_list.append(temp)
        print("성공:", os.path.basename(file), temp.shape)

    except Exception as e:
        failed_files.append((os.path.basename(file), str(e)))
        print("실패:", os.path.basename(file), e)

print("성공 파일 수:", len(df_list))
print("실패 파일 수:", len(failed_files))

if len(df_list) > 0:
    df_reviews = pd.concat(df_list, ignore_index=True)
    print("최종 데이터 크기:", df_reviews.shape)
    display(df_reviews.head())
else:
    print("합칠 데이터가 없습니다. file_list 경로를 다시 확인하세요.")

찾은 파일 수: 31
['C:\\Users\\hmabc\\Downloads\\myd_reviews\\reviews_reviews_io.snplab.myd_202305.csv', 'C:\\Users\\hmabc\\Downloads\\myd_reviews\\reviews_reviews_io.snplab.myd_202306.csv', 'C:\\Users\\hmabc\\Downloads\\myd_reviews\\reviews_reviews_io.snplab.myd_202307.csv']
성공: reviews_reviews_io.snplab.myd_202305.csv (78, 18)
성공: reviews_reviews_io.snplab.myd_202306.csv (47, 18)
성공: reviews_reviews_io.snplab.myd_202307.csv (65, 18)
성공: reviews_reviews_io.snplab.myd_202308.csv (113, 18)
성공: reviews_reviews_io.snplab.myd_202309.csv (50, 18)
성공: reviews_reviews_io.snplab.myd_202310.csv (56, 18)
성공: reviews_reviews_io.snplab.myd_202311.csv (55, 18)
성공: reviews_reviews_io.snplab.myd_202312.csv (69, 18)
성공: reviews_reviews_io.snplab.myd_202401.csv (63, 18)
성공: reviews_reviews_io.snplab.myd_202402.csv (27, 18)
성공: reviews_reviews_io.snplab.myd_202403.csv (21, 18)
성공: reviews_reviews_io.snplab.myd_202404.csv (25, 18)
성공: reviews_reviews_io.snplab.myd_202405.csv (23, 18)
성공: reviews_reviews_io.snplab.myd_202406.csv (11, 18)
성공: reviews_reviews_io.snplab.myd_202407.csv (16, 18)
성공: reviews_reviews_io.snplab.myd_202408.csv (12, 18)
성공: reviews_reviews_io.snplab.myd_202409.csv (5, 18)
성공: reviews_reviews_io.snplab.myd_202410.csv (17, 18)
성공: reviews_reviews_io.snplab.myd_202411.csv (9, 18)
성공: reviews_reviews_io.snplab.myd_202412.csv (14, 18)
성공: reviews_reviews_io.snplab.myd_202501.csv (10, 18)
성공: reviews_reviews_io.snplab.myd_202502.csv (7, 18)
성공: reviews_reviews_io.snplab.myd_202503.csv (4, 18)
성공: reviews_reviews_io.snplab.myd_202504.csv (9, 18)
성공: reviews_reviews_io.snplab.myd_202505.csv (8, 18)
성공: reviews_reviews_io.snplab.myd_202506.csv (3, 18)
성공: reviews_reviews_io.snplab.myd_202507.csv (3, 18)
성공: reviews_reviews_io.snplab.myd_202508.csv (40, 18)
성공: reviews_reviews_io.snplab.myd_202601.csv (18, 18)
성공: reviews_reviews_io.snplab.myd_202604.csv (6, 18)
성공: reviews_reviews_io.snplab.myd_202605.csv (11, 18)
성공 파일 수: 31
실패 파일 수: 0
최종 데이터 크기: (895, 18)

,Package Name,App Version Code,App Version Name,Reviewer Language,Device,Review Submit Date and Time,Review Submit Millis Since Epoch,Review Last Update Date and Time,Review Last Update Millis Since Epoch,Star Rating,Review Title,Review Text,Developer Reply Date and Time,Developer Reply Millis Since Epoch,Developer Reply Text,Review Link,review_month,source_file
0,io.snplab.myd,230427001.0,2.3.3-prod-rel-202304270020,ko,a8sqlteks,2023-05-01T02:11:40Z,1682907100167,2023-05-01T02:11:40Z,1682907100167,4,NaN,조아요,2023-05-02T06:43:14Z,1.683010e+12,"안녕하세요 모름님, 마이디입니다. 먼저 , 저희 앱을 좋아 해주셔 감사합니다. 앞으...",http://play.google.com/console/developers/8861...,202305,reviews_reviews_io.snplab.myd_202305.csv
1,io.snplab.myd,230427001.0,2.3.3-prod-rel-202304270020,ko,o1s,2023-05-01T11:01:02Z,1682938862348,2023-05-01T11:01:02Z,1682938862348,5,NaN,NaN,NaN,NaN,NaN,NaN,202305,reviews_reviews_io.snplab.myd_202305.csv
2,io.snplab.myd,230427001.0,2.3.3-prod-rel-202304270020,ko,t2s,2023-05-01T11:57:27Z,1682942247763,2023-05-01T11:57:27Z,1682942247763,5,NaN,NaN,NaN,NaN,NaN,NaN,202305,reviews_reviews_io.snplab.myd_202305.csv
3,io.snplab.myd,230427001.0,2.3.3-prod-rel-202304270020,ko,b2q,2023-05-01T12:51:10Z,1682945470101,2023-05-01T12:51:10Z,1682945470101,5,NaN,NaN,NaN,NaN,NaN,NaN,202305,reviews_reviews_io.snplab.myd_202305.csv
4,io.snplab.myd,230427001.0,2.3.3-prod-rel-202304270020,ko,g0q,2023-05-02T04:51:40Z,1683003100146,2023-05-02T04:51:40Z,1683003100146,4,NaN,NaN,NaN,NaN,NaN,NaN,202305,reviews_reviews_io.snplab.myd_202305.csv

In [6]:
df_reviews = pd.concat(df_list, ignore_index=True)

print(df_reviews.shape)
df_reviews.head()

(895, 18)

,Package Name,App Version Code,App Version Name,Reviewer Language,Device,Review Submit Date and Time,Review Submit Millis Since Epoch,Review Last Update Date and Time,Review Last Update Millis Since Epoch,Star Rating,Review Title,Review Text,Developer Reply Date and Time,Developer Reply Millis Since Epoch,Developer Reply Text,Review Link,review_month,source_file
0,io.snplab.myd,230427001.0,2.3.3-prod-rel-202304270020,ko,a8sqlteks,2023-05-01T02:11:40Z,1682907100167,2023-05-01T02:11:40Z,1682907100167,4,NaN,조아요,2023-05-02T06:43:14Z,1.683010e+12,"안녕하세요 모름님, 마이디입니다. 먼저 , 저희 앱을 좋아 해주셔 감사합니다. 앞으...",http://play.google.com/console/developers/8861...,202305,reviews_reviews_io.snplab.myd_202305.csv
1,io.snplab.myd,230427001.0,2.3.3-prod-rel-202304270020,ko,o1s,2023-05-01T11:01:02Z,1682938862348,2023-05-01T11:01:02Z,1682938862348,5,NaN,NaN,NaN,NaN,NaN,NaN,202305,reviews_reviews_io.snplab.myd_202305.csv
2,io.snplab.myd,230427001.0,2.3.3-prod-rel-202304270020,ko,t2s,2023-05-01T11:57:27Z,1682942247763,2023-05-01T11:57:27Z,1682942247763,5,NaN,NaN,NaN,NaN,NaN,NaN,202305,reviews_reviews_io.snplab.myd_202305.csv
3,io.snplab.myd,230427001.0,2.3.3-prod-rel-202304270020,ko,b2q,2023-05-01T12:51:10Z,1682945470101,2023-05-01T12:51:10Z,1682945470101,5,NaN,NaN,NaN,NaN,NaN,NaN,202305,reviews_reviews_io.snplab.myd_202305.csv
4,io.snplab.myd,230427001.0,2.3.3-prod-rel-202304270020,ko,g0q,2023-05-02T04:51:40Z,1683003100146,2023-05-02T04:51:40Z,1683003100146,4,NaN,NaN,NaN,NaN,NaN,NaN,202305,reviews_reviews_io.snplab.myd_202305.csv

In [7]:
df_reviews.shape

(895, 18)

In [8]:
df_reviews.columns

Index(['Package Name', 'App Version Code', 'App Version Name',
       'Reviewer Language', 'Device', 'Review Submit Date and Time',
       'Review Submit Millis Since Epoch', 'Review Last Update Date and Time',
       'Review Last Update Millis Since Epoch', 'Star Rating', 'Review Title',
       'Review Text', 'Developer Reply Date and Time',
       'Developer Reply Millis Since Epoch', 'Developer Reply Text',
       'Review Link', 'review_month', 'source_file'],
      dtype='str')

In [9]:
df_reviews['review_month'].value_counts().sort_index()

review_month
202305     78
202306     47
202307     65
202308    113
202309     50
202310     56
202311     55
202312     69
202401     63
202402     27
202403     21
202404     25
202405     23
202406     11
202407     16
202408     12
202409      5
202410     17
202411      9
202412     14
202501     10
202502      7
202503      4
202504      9
202505      8
202506      3
202507      3
202508     40
202601     18
202604      6
202605     11
Name: count, dtype: int64

In [10]:
keep_cols = [
    'review_month',
    'Review Submit Date and Time',
    'Star Rating',
    'Review Text',
    'Reviewer Language',
    'Device',
    'App Version Name'
]

df_reviews = df_reviews[keep_cols].copy()

In [11]:
df_reviews['Review Text'] = df_reviews['Review Text'].fillna('')

df_reviews = df_reviews[
    df_reviews['Review Text'].str.strip() != ''
]

In [12]:
df_reviews['Review Submit Date and Time'] = pd.to_datetime(
    df_reviews['Review Submit Date and Time']
)

In [13]:
print(df_reviews.shape)

df_reviews.head()

(200, 7)

,review_month,Review Submit Date and Time,Star Rating,Review Text,Reviewer Language,Device,App Version Name
0,202305,2023-05-01 02:11:40+00:00,4,조아요,ko,a8sqlteks,2.3.3-prod-rel-202304270020
21,202305,2023-05-07 09:56:59+00:00,2,포인트가 많이 모이는건 좋은데 이상하게 이 앱을 설치하고 금융기관 연결 하고 나니까...,ko,beyond2,2.3.3-prod-rel-202304270020
22,202305,2023-03-05 17:22:13+00:00,5,혹시 지마켓 카카오계정은 어떻게 로그인하나용?,ko,b4q,2.3.3-prod-rel-202304270020
42,202305,2023-05-13 08:38:16+00:00,5,좋네요,ko,dm1q,2.3.3-prod-rel-202304270020
45,202305,2023-05-14 00:59:27+00:00,3,뭘 리뷰하라는건지?,ko,d2x,2.3.3-prod-rel-202304270020

In [14]:
df_reviews['Reviewer Language'].value_counts()

Reviewer Language
ko    193
en      4
ar      1
fa      1
hi      1
Name: count, dtype: int64

In [15]:
df_reviews = df_reviews[
    df_reviews['Reviewer Language'] == 'ko'
]

In [16]:
df_reviews['Star Rating'].value_counts().sort_index()

Star Rating
1    75
2    20
3    22
4    23
5    53
Name: count, dtype: int64

In [17]:
df_reviews.shape
df_reviews['Star Rating'].value_counts().sort_index()
df_reviews['Reviewer Language'].value_counts()

Reviewer Language
ko    193
Name: count, dtype: int64

In [18]:
df_reviews.shape

(193, 7)

## 버전별 평점 분석

In [19]:
version_rating = (
    df_reviews.groupby('App Version Name')['Star Rating']
    .agg(['count','mean'])
)

version_rating = version_rating[
    version_rating['count'] >= 5
].sort_values('count', ascending=False)

version_rating

                             count      mean
App Version Name
3.3.10-rel-20250617             26  2.961538
3.0.5-rel-20240109              11  2.000000
3.0.0-rel-20231030              10  2.700000
3.0.2-rel-20231127              10  2.300000
2.4.3-prod-rel-202309201552      9  4.777778
2.3.3-prod-rel-202304270020      9  3.222222
3.3.12-rel-20250916              8  1.875000
2.3.9-prod-rel-202307141628      8  2.375000
2.4.2-prod-rel-202308301751      6  3.666667
3.0.4-rel-20231228               6  2.666667
3.3.14-rel-20260113              6  4.833333
3.0.3-rel-20231218               5  2.600000
3.0.7-rel-20240223               5  2.800000
3.3.16-rel-20260422              5  2.200000

In [20]:
v3310 = df_reviews[
    df_reviews['App Version Name'] == '3.3.10-rel-20250617'
]

v3310[['Star Rating','Review Text']]

     Star Rating                                        Review Text
817            2                                   잘쓰고있었는데 업뎃후로그인안됨
822            4            휴대폰 교체후 앱 새로 깔았는데 전에있던 포인트가 다 날라가버렸어요..
823            5  포인트를 사용해서 네이버페이를 구매하려는데 오류가 발생해서 구매가 안 됩니다 해결해...
825            1  8.16부터 포인트 적립 하나도안되고 포인트는 0포인트로 날라갔네요 문의하기해도 문...
826            5  하루밤사이에 포인트가 다사라져있길래 고객센터 문의글올리려고했더니 글도 업로드가안되고...
827            1  아니 어제까지만 해도 잘 쌓이던 포인트가 0으로 돌아가있네요; 오류인가 싶어서 껐다...
828            1                      모아둔 포인트가 0으로 보이는데 복구 부탁 드립니다.
829            2                   다시 깔았는데 왜 시작이 안될까요?허용다 했는데 안넘어가고
830            4  잘 사용하고 있었는데 단 몇시간만에 포인트가 사라졌어요 문의하기도 오류 때문에 안되...
833            1  갑자기 본인인증 하라더니 포인트 제로되고, 문의하기도 오류뜨고.... 삭제 후 재설...
834            3  잘 쓰고 있었는데 갑자기 포인트가 날아갔어요... 고객센터에 문의하려고 했지만 앱 ...
835            1  어제까지만 해도 4천 포인트 넘게 보유 중이던 내 포인트가 지금 확인하니 0으로 표...
836            4  갑자기 마케팅 정보 수신 동의도 미동의도 안되고 포인트가 0이 되어버리고 문의하기도...
839            2                       갑자기 포인트가 다 날라갔는데 문의하기도 안돼요..
843            5  포인트가 0이 되었고 금일 참여한 포인트도 적립은 되었다고 확인은 되는데 적립은 되...
845            1                                  갑자기 포인트가 다 사라졌습니다
847            1            포인트가 사라졌어요. 답변 보고 문의하기를 눌러도 전송 실패라고 뜹니다
850            1  안녕하세요. 오늘 새벽 4시쯤에 출석 체크를 했는데 적립포인트가 0가 되어 있었어요...
851            5  문의하기에 글올리려해도 오류나서 안올라가서 여기 남깁니다 본인인증후 있던 포인트 다...
852            2                한동안 잘 사용하고 있었는데 포인트 사라지고 정립도 안되네 ㅋㅋ
853            5                포인트가 다 날아갔는데 문의하기 글도 안써지고 이게 무슨일인가요
854            5  문의하기누르면 문의하기에 실패하였습니다만 뜨고 보유포인트는 업데이트후 아무리 활동해...
855            3  걸음수 측정이 몇일째 안되고 있습니다 해결 방법을 알려주세요. 문의하기도 계속 실패...
856            4                        만보기기능이측정이하나도안되요.최근오류이슈이후로요.
857            4  구글 연결도 계속 실패하고 탈퇴 하고 싶어도 탈퇴표시가 없네요 그리고 고객센터 문의...
858            5                                                좋아요

In [23]:
v3310 = df_reviews[
    df_reviews['App Version Name'] == '3.3.12-rel-20250916'
]

v3310[['Star Rating','Review Text']]

     Star Rating                                        Review Text
860            1                                    오늘출석체크가안들어가지내요.
861            3                    오늘 출석체크가 안눌려요 왜이래요 ㅠ 내 포인트으으으으으
862            1            도망갔어요? 앱내 문의하기도 안되게 막아놓고 지금 출첵이 안된다고요;;
863            2  어제까지 잘 사용했던 어플이었는데 출석체크만 눌러도 안들어가져요 업테이트까지 다 했...
864            1                                    지금 출첵 버튼이 안보입니다
865            1                                         출석체크가 안됩니다
866            1          오류가 많고 쓰레기 같은 어플 포인트 주기 싫어서 개수작 부리는 어플!!!
867            5                                      빠른조치 감사해요~~^^

In [24]:
v3310 = df_reviews[
    df_reviews['App Version Name'] == '3.3.14-rel-20260113'
]

v3310[['Star Rating','Review Text']]

     Star Rating                                        Review Text
869            5       개인정보 유출이 걱정되는 시대에 꼭 필요한 기능을 가진 앱이네요~~ 화이팅하세요
870            5  솔직히 반신반의했는데 진짜 돈이 됨;; 다른 앱처럼 1원 2원 주는 게 아니라 단위...
872            4  앱 사용하면서 얻는 포인트나 혜택들이 쏠쏠하네요. 오류가 있긴 하지만 도움이 되는 ...
873            5  만보기 앱으누다른 앱들도 쓰는데, 이건 만보기말고도 다른 데이터를 한눈에 볼 수있어...
874            5                               설명이잘되어있어서 사용하기 편해요!!
877            5  출책 적립되는 재미가 있어서 잘 쓰고 있습니다 ㅎ 포인트는 주로 커피 사먹는데 쓰게...

In [25]:
v3310 = df_reviews[
    df_reviews['App Version Name'] == '3.3.16-rel-20260422'
]

v3310[['Star Rating','Review Text']]

     Star Rating                                        Review Text
886            1                          포인트몰이 이상하네여 구지 이상하게 업데이트를
887            1  업데이트후 많이 안좋아졌네요 네이버페이 쿠폰도 5000원부터 안되고 1만원부터 뽑을...
888            4  포인트몰이 안보여요.쇼핑 채널로 가서 쓰라는데, 편의점 상품권같은거로 바꿔서 유용하...
891            1  갑자기 포인트몰은 왜 없앤겁니까? 포인트몰 없애고 무슨 쇼핑몰? 같은걸로 바뀐거 같...
892            4  출석해도 포인트 주고 다양하게 적립 되고 깔끔하고 좋아요 그런데 요즘 네이버페이교환...